# Generated by Django 3.2.4 on 2021-06-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(choices=[('med', 'med'), ('para', 'para'), ('diet', 'diet')], max_length=20, null=True)),
                ('forme', models.CharField(choices=[('comprime', 'comprime'), ('sirop', 'sirop'), ('suppo', 'suppo'), ('inj', 'inj')], max_length=15, null=True)),
                ('ppv', models.FloatField(null=True)),
                ('pph', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
